version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: password
      POSTGRES_DB: greenlight_db
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: